/* OZON 畅销商品批量查询 · 前端逻辑 */
(function(){
  'use strict';
  const API_URL='https://api.seller.ozon.ru/api/site/seller-analytics/what_to_sell/data/v3';
  const $=function(s){return document.querySelector(s);};
  const els={
    tabs:document.querySelectorAll('.tab'),
    panels:document.querySelectorAll('.tab-panel'),
    inputs:{ids:$('#input-ids'),links:$('#input-links'),table:$('#input-table')},
    batch:$('#batch-size'),concurrency:$('#concurrency'),interval:$('#interval'),
    run:$('#run-btn'),stop:$('#stop-btn'),exportCsv:$('#export-csv'),exportJson:$('#export-json'),clear:$('#clear-btn'),
    status:$('#status'),statusText:$('#status-text'),progressBar:$('#progress-bar'),progressText:$('#progress-text'),
    table:$('#result-table'),body:$('#result-body'),count:$('#result-count'),
    filter:$('#filter-input'),sortKey:$('#sort-key'),
  };
  const state={rows:[],aborted:false,running:false,seenSku:new Set()};
  els.tabs.forEach(function(t){t.addEventListener('click',function(){els.tabs.forEach(function(x){x.classList.toggle('active',x===t);});els.panels.forEach(function(p){p.classList.toggle('active',p.dataset.tab===t.dataset.tab);});});});
  function currentInput(){var active=document.querySelector('.tab-panel.active'); if(!active)return ''; return els.inputs[active.dataset.tab].value||'';}
  function parseIds(){var raw=currentInput(); var items=raw.split(/[\s,;\t\n]+/).map(function(s){return s.replace(/^["\'\`]+|["\'\`]+$/g,'').trim();}).filter(Boolean); var seen={}; var out=[]; for(var i=0;i<items.length;i++){var n=extractSku(items[i]); if(n && !seen[n]){seen[n]=1; out.push(n);}} return out;}
  function extractSku(t){if(!t)return ''; var m=t.match(/ozon\.ru\/product\/(\d{5,12})/i); if(m)return m[1]; var m2=t.match(/(?:^|\b)(?:sku|id|product)[ _:=-]+(\d{5,12})\b/i); if(m2)return m2[1]; var m3=t.match(/\b(\d{5,12})\b/); return m3?m3[1]:'';}
  async function callOne(sku,signal){var body={limit:'50',offset:'0',filter:{stock:'any_stock',period:'weekly',categories:[],sku:sku},sort:{key:'sum_missed_gmv',order:'desc'}}; var r=await fetch(API_URL,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json',Accept:'application/json, text/plain, */*','x-o3-app-name':'seller-ui','x-o3-language':'zh-Hans','x-o3-page-type':'analytics_platform'},body:JSON.stringify(body),signal:signal}); if(!r.ok){throw new Error('HTTP '+r.status);} var j=await r.json(); return Array.isArray(j.items)?j.items:[];}
  async function runOne(sku,signal){for(var i=0;i<3;i++){if(state.aborted)throw new Error('aborted'); try{return await callOne(sku,signal);}catch(e){await new Promise(function(r){setTimeout(r,600*(i+1));});} } throw new Error('sku failed');}
  async function pool(items,limit,fn){var q=items.slice(); var w=new Array(Math.min(limit,q.length)).fill(0).map(async function(){while(q.length && !state.aborted){var it=q.shift(); try{await fn(it);}catch(e){console.warn(e);}}}); await Promise.all(w);}
  function fmtRow(it){return{sku:it.sku||'',name:it.name||'',brand:it.brand||'',category1:it.category1||'',category2:it.category2||'',category3:it.category3||'',link:it.link||'',photo:it.photo||'',gmvSum:Number(it.gmvSum||0),soldCount:Number(it.soldCount||0),minSellerPrice:Number(it.minSellerPrice||0),avgGmv:Number(it.avgGmv||0),sumMissedGmv:Number(it.sumMissedGmv||0),salesDynamics:Number(it.nullableSalesDynamics??it.salesDynamics??0),avgGmvOnAccDays:Number(it.avgGmvOnAccDays||0),avgOrdersOnAccDays:Number(it.avgOrdersOnAccDays||0),sessionCountSearch:Number(it.sessionCountSearch||0),sessionCount:Number(it.sessionCount||0),convToCartSearch:Number(it.convToCartSearch||0),pdpToCartConversion:Number(it.pdpToCartConversion||0),advCostShare:Number(it.advCostShare||0),nullableBuyoutShare:Number(it.nullableBuyoutRate??it.nullableBuyoutShare??0),nullableCreateDate:it.nullableCreateDate||'',fboCommission:Number(it.fboCommission||0),fbsCommission:Number(it.fbsCommission||0),salesSchema:it.salesSchema||'',volume:Number(it.volume||0)};}
  function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return {'&':'&','<':'<','>':'>','"':'"','\'':'''}[c];});}
  function render(){var f=(els.filter.value||'').toLowerCase(); var sk=els.sortKey.value; var rows=state.rows.slice(); if(f){rows=rows.filter(function(r){return [r.sku,r.name,r.brand,r.category3,r.category1].some(function(x){return String(x||'').toLowerCase().indexOf(f)>=0;});});} rows.sort(function(a,b){return (b[sk]||0)-(a[sk]||0);}); els.count.textContent=rows.length; els.body.innerHTML=rows.length?'':'<tr class="empty"><td colspan="12">'+(state.rows.length?'过滤无结果':'暂无数据')+'</td></tr>'; var f2=document.createDocumentFragment(); rows.forEach(function(r,i){var tr=document.createElement('tr'); tr.innerHTML='<td>'+(i+1)+'</td><td class="sku"><a href="'+r.link+'" target="_blank">'+r.sku+'</a></td><td><div class="product-cell">'+(r.photo?'<img src="'+r.photo+'" loading="lazy" />':'')+'<span>'+esc(r.name)+'</span></div></td><td>'+(esc(r.brand)||'-')+'</td><td>'+(esc(r.category3)||esc(r.category1)||'-')+'</td><td>'+(r.gmvSum||0).toLocaleString()+'</td><td>'+(r.soldCount||0).toLocaleString()+'</td><td>'+(r.avgGmv||0).toLocaleString()+'</td><td>'+(r.sumMissedGmv||0).toLocaleString()+'</td><td>'+r.salesDynamics+'%</td><td>'+(r.pdpToCartConversion||0).toFixed(2)+'%</td><td><a href="'+r.link+'" target="_blank">查看</a></td>'; f2.appendChild(tr);}); els.body.appendChild(f2); els.exportCsv.disabled=state.rows.length===0; els.exportJson.disabled=state.rows.length===0;}
  function setStatus(cls,text){els.status.classList.remove('running','success','error'); if(cls)els.status.classList.add(cls); els.statusText.textContent=text;}
  function setProgress(d,t){var pct=t?Math.min(100,Math.round(d/t*100)):0; els.progressBar.style.setProperty('--p',pct+'%'); els.progressText.textContent=d+' / '+t;}
  function clamp(n,mn,mx){n=Number(n); if(isNaN(n))return mn; return Math.max(mn,Math.min(mx,n));}
  async function run(){if(state.running)return; var ids=parseIds(); if(!ids.length){setStatus('error','没有解析到 ID'); return;} state.rows=[]; state.aborted=false; state.seenSku=new Set(); state.running=true; els.run.disabled=true; els.stop.disabled=false; setStatus('running','开始查询 '+ids.length+' 个 ID ...'); var bs=clamp(parseInt(els.batch.value)||30,1,100); var iv=clamp(parseInt(els.interval.value)||200,0,5000); var cc=clamp(parseInt(els.concurrency.value)||3,1,8); var done=0; var total=ids.length; var ac=new AbortController(); state._ac=ac; try{setProgress(0,total); for(var i=0;i<ids.length;i+=bs){if(state.aborted)break; var batch=ids.slice(i,i+bs); await pool(batch,cc,async function(sku){if(state.aborted)return; try{var items=await runOne(sku,ac.signal); for(var j=0;j<items.length;j++){var r=fmtRow(items[j]); if(!state.seenSku.has(r.sku)){state.seenSku.add(r.sku); state.rows.push(r);}}}catch(e){console.warn(sku,e);} done++; setProgress(done,total); render(); if(iv>0)await new Promise(function(res){setTimeout(res,iv);});});} setStatus(state.aborted?'error':'success',(state.aborted?'已停止 ·共 ':'完成 ·共 ')+state.rows.length+' 条');}catch(e){setStatus('error','失败: '+e.message);} finally{state.running=false; els.run.disabled=false; els.stop.disabled=true;}}
  function exportCsv(){var headers=['sku','name','brand','category1','category2','category3','link','photo','gmvSum','soldCount','minSellerPrice','avgGmv','sumMissedGmv','salesDynamics','avgGmvOnAccDays','avgOrdersOnAccDays','sessionCountSearch','sessionCount','convToCartSearch','pdpToCartConversion','advCostShare','nullableBuyoutShare','nullableCreateDate','fboCommission','fbsCommission','salesSchema','volume']; var e=function(v){var s=String(v==null?'':v); return /[",\n]/.test(s)?('"'+s.replace(/"/g,'""')+'"'):s;}; var out=[headers.join(',')]; for(var i=0;i<state.rows.length;i++){out.push(headers.map(function(k){return e(state.rows[i][k]);}).join(','));} download('\ufeff'+out.join('\n'),'ozon-wts-result.csv','text/csv;charset=utf-8');}
  function exportJson(){download(JSON.stringify(state.rows,null,2),'ozon-wts-result.json','application/json');}
  function download(text,name,mime){var blob=new Blob([text],{type:mime}); var url=URL.createObjectURL(blob); var a=document.createElement('a'); a.href=url; a.download=name; document.body.appendChild(a); a.click(); document.body.removeChild(a); setTimeout(function(){URL.revokeObjectURL(url);},500);}
  els.run.addEventListener('click',run);
  els.stop.addEventListener('click',function(){state.aborted=true; if(state._ac)state._ac.abort(); setStatus('error','正在停止...');});
  els.clear.addEventListener('click',function(){if(state.running)return; for(var k in els.inputs)els.inputs[k].value=''; state.rows=[]; render(); setStatus('error','等待输入...'); setProgress(0,0);});
  els.exportCsv.addEventListener('click',exportCsv);
  els.exportJson.addEventListener('click',exportJson);
  els.filter.addEventListener('input',render);
  els.sortKey.addEventListener('change',render);
  render();
})();
